### ISSUE TITLE
Device research failed

### ISSUE THREAD

**Issue by Neptunium16** [ion201/PyHSCam#1]
Hi !

I've got an issue trying to open device connection by IP. **PyHSCam.openDeviceByIp('**ip address**')** can't find the device whereas **Photron FastCam Viewer** reaches it for the same IP address.

I executed:
<code>>>> import PyHSCam as cam</code>
<code>>>> cam.init()</code>
<code>>>> cam.openDeviceByIp('192.168.0.1')</code>
<code>Traceback (most recent call last):</code>
<code>  File "\<stdin\>", line 1, in \<module\></code>
<code>PyHSCam.CamRuntimeError: SDK reported 0 devices found!</code>

Could you help me please ?

**Comment by ion201** [comment]
First, please ensure that there is an exception for python through the windows firewall. Otherwise the firewall will block traffic from python. 

I don't think this requires administrator privileges, but I honestly can't remember.

Also, please note that I no longer develop on windows nor do I have access to a camera to use with this module so this repo might as well be archived.

**Comment by Neptunium16** [comment]
Issue solved !
The IP address should be written, in my case, with 3 digits for each of the four groups '**192.168.000.010**' instead of '**192.168.0.1**'.
Now all functions are working.
Thank you for your code and your response.
